# Generated by Django 4.2.17 on 2025-03-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20250213_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('directores', models.ManyToManyField(related_name='peliculas', through='movies.DirectorPelicula', to='movies.director')),
            ],
        ),
        migrations.AddField(
            model_name='directorpelicula',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.pelicula'),
        ),
    ]
