# Generated by Django 4.2.17 on 2025-03-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_directorpelicula_pelicula_directorpelicula_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='directores',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.DeleteModel(
            name='DirectorPelicula',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.AddField(
            model_name='directormovie',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directores',
            field=models.ManyToManyField(related_name='movies_director', through='movies.DirectorMovie', to='movies.director'),
        ),
    ]
